### PR TITLE
errors with messages in editor [RIP-41]

### PR DESCRIPTION
**Pull request by AlexWeinstein92**
The error highlighting seen in the screenshot below has been ensured & tested to:
- be generated for whichever file is open during running the `from` command
- be generated when a file with an error is opened
  - from a link in the RIDDL run window
  - manually by a user

Screenshot 2024-10-23 at 11 46 11 AM

### CODE REVIEW

**Comment by reid-spencer** [comment]
The error highlighting should also be done in the form of a pop-up that occurs when the mouse hovers over the error location. Is that what's happening in your screenshot?

**Comment by reid-spencer** [comment]
The red line in the scoll column looks correct.

**Review by reid-spencer — CHANGES_REQUESTED** [review]
Answers are needed before this can be approved.

**Comment by AlexWeinstein92** [comment]
@reid-spencer I am indeed using the logger messages for generating error messages, and yes, when I wrote "for the open file", I could have qualified it as "for the open file, if there is an error generated for it". You also have it correct that my mouse is hovering to reveal the message in my screenshot

**Review by reid-spencer — APPROVED** [review]
Approved based on continuing plan to resolve this

**Pull request merged**
